/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases_Principales;

import Clases_SQL.ConexionBD;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aleja
 */
public class AGREGAR_Administrador extends javax.swing.JFrame {
    private final String base = "Registro_de_inscripcion_IUNIS";
    private final String user = "postgres";
    private final String password = "adminfile84";
    private final String url = "jdbc:postgresql://localhost:5432/" + base;
    private Connection Conectar = null;
    

    ConexionBD con = new ConexionBD();
    public Connection getConexion() {
        try {
            Class.forName("org.postgresql.Driver");
            Conectar = DriverManager.getConnection(url, user, password);
            JOptionPane.showMessageDialog(null, "Conexion exitosa");
              
        } catch (ClassNotFoundException ex) {
            System.err.println(ex);
            Logger.getLogger(ConexionBD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ConexionBD.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Conectar;

    }
    
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;

    public AGREGAR_Administrador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Apellidos = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Correo = new javax.swing.JLabel();
        jLabel_Password = new javax.swing.JLabel();
        Ingresar_Password_Admin = new javax.swing.JTextField();
        Ingresar_Correo_Admin = new javax.swing.JTextField();
        Ingresar_Apellidos_Admin = new javax.swing.JTextField();
        Ingresar_Nombre_Admin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Boton_Guardar = new javax.swing.JButton();
        jLabel_Marco_gris4 = new javax.swing.JLabel();
        jLabel_Marco_gris3 = new javax.swing.JLabel();
        jLabel_Marco_gris2 = new javax.swing.JLabel();
        jLabel_Marco_gris1 = new javax.swing.JLabel();
        jLabel_Agregar_Administrador = new javax.swing.JLabel();
        jLabel_Fondo_azul_negro = new javax.swing.JLabel();
        jLabel_Fondo_blanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar administrador - LogBook");
        setMinimumSize(new java.awt.Dimension(546, 530));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel_Apellidos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel_Apellidos.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Apellidos.setText("Apellidos:");
        getContentPane().add(jLabel_Apellidos);
        jLabel_Apellidos.setBounds(20, 170, 110, 30);

        jLabel_Nombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel_Nombre.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Nombre.setText("Nombre(s):");
        getContentPane().add(jLabel_Nombre);
        jLabel_Nombre.setBounds(20, 90, 120, 30);

        jLabel_Correo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel_Correo.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Correo.setText("Email:");
        getContentPane().add(jLabel_Correo);
        jLabel_Correo.setBounds(20, 250, 80, 30);

        jLabel_Password.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel_Password.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Password.setText("Contraseña:");
        getContentPane().add(jLabel_Password);
        jLabel_Password.setBounds(20, 330, 120, 30);

        Ingresar_Password_Admin.setBackground(new java.awt.Color(246, 246, 246));
        Ingresar_Password_Admin.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        getContentPane().add(Ingresar_Password_Admin);
        Ingresar_Password_Admin.setBounds(150, 330, 360, 35);

        Ingresar_Correo_Admin.setBackground(new java.awt.Color(246, 246, 246));
        Ingresar_Correo_Admin.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        getContentPane().add(Ingresar_Correo_Admin);
        Ingresar_Correo_Admin.setBounds(150, 250, 360, 35);

        Ingresar_Apellidos_Admin.setBackground(new java.awt.Color(246, 246, 246));
        Ingresar_Apellidos_Admin.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        getContentPane().add(Ingresar_Apellidos_Admin);
        Ingresar_Apellidos_Admin.setBounds(150, 170, 360, 35);

        Ingresar_Nombre_Admin.setBackground(new java.awt.Color(246, 246, 246));
        Ingresar_Nombre_Admin.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        getContentPane().add(Ingresar_Nombre_Admin);
        Ingresar_Nombre_Admin.setBounds(150, 90, 360, 35);

        jButton1.setBackground(new java.awt.Color(7, 43, 78));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_del_Registro_Escolar/Logo volver blanco CHICO.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 10, 50, 40);

        Boton_Guardar.setBackground(new java.awt.Color(0, 153, 0));
        Boton_Guardar.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        Boton_Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Boton_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_del_Registro_Escolar/Icono Guardar INFO CHICO.png"))); // NOI18N
        Boton_Guardar.setText("Guardar");
        Boton_Guardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Boton_Guardar.setIconTextGap(8);
        Boton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_Guardar);
        Boton_Guardar.setBounds(379, 440, 151, 50);

        jLabel_Marco_gris4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel_Marco_gris4);
        jLabel_Marco_gris4.setBounds(10, 320, 520, 60);

        jLabel_Marco_gris3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel_Marco_gris3);
        jLabel_Marco_gris3.setBounds(10, 240, 520, 60);

        jLabel_Marco_gris2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel_Marco_gris2);
        jLabel_Marco_gris2.setBounds(10, 160, 520, 60);

        jLabel_Marco_gris1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel_Marco_gris1);
        jLabel_Marco_gris1.setBounds(10, 80, 520, 60);

        jLabel_Agregar_Administrador.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel_Agregar_Administrador.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Agregar_Administrador.setText("Agregar administrador");
        getContentPane().add(jLabel_Agregar_Administrador);
        jLabel_Agregar_Administrador.setBounds(130, 10, 310, 40);

        jLabel_Fondo_azul_negro.setBackground(new java.awt.Color(7, 43, 78));
        jLabel_Fondo_azul_negro.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_Fondo_azul_negro.setOpaque(true);
        getContentPane().add(jLabel_Fondo_azul_negro);
        jLabel_Fondo_azul_negro.setBounds(0, 0, 540, 60);

        jLabel_Fondo_blanco.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Fondo_blanco.setOpaque(true);
        getContentPane().add(jLabel_Fondo_blanco);
        jLabel_Fondo_blanco.setBounds(0, 60, 540, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu_Principal_ADMINISTRADOR Menu = new Menu_Principal_ADMINISTRADOR();
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Boton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_GuardarActionPerformed
        Connection con = null;
        
        try {
            con = getConection();
            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_Boton_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AGREGAR_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AGREGAR_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AGREGAR_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AGREGAR_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AGREGAR_Administrador().setVisible(true);
            }
        });
    }

//    void Agregar() {
//        String Nombre = Ingresar_Nombre_Admin.getText();
//        String Apellidos = Ingresar_Apellidos_Admin.getText();
//        String Correo = Ingresar_Correo_Admin.getText();
//        String Password = Ingresar_Password_Admin.getText();
//
//        if (Nombre.equals("") || Apellidos.equals("") || Correo.equals("") || Password.equals("")) {
//            JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios");
//        } else {
//            String sql = "INSERT INTO Datos_administradores(nombre_admin,apellido_admin,correo_admin_password_admin)VALUES('" + Nombre + "','" + Apellidos + "','" + Correo + "','" + Password + "')";
//
//            try {
//                cn = con.getConexion();
//                st = cn.createStatement();
//                st.executeUpdate(sql);
//
//            } catch (Exception e) {
//            }
//
//        }
//
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Guardar;
    private javax.swing.JTextField Ingresar_Apellidos_Admin;
    private javax.swing.JTextField Ingresar_Correo_Admin;
    private javax.swing.JTextField Ingresar_Nombre_Admin;
    private javax.swing.JTextField Ingresar_Password_Admin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel_Agregar_Administrador;
    private javax.swing.JLabel jLabel_Apellidos;
    private javax.swing.JLabel jLabel_Correo;
    private javax.swing.JLabel jLabel_Fondo_azul_negro;
    private javax.swing.JLabel jLabel_Fondo_blanco;
    private javax.swing.JLabel jLabel_Marco_gris1;
    private javax.swing.JLabel jLabel_Marco_gris2;
    private javax.swing.JLabel jLabel_Marco_gris3;
    private javax.swing.JLabel jLabel_Marco_gris4;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Password;
    // End of variables declaration//GEN-END:variables
}
