/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases_Principales;

import javax.swing.JOptionPane;

/**
 *
 * @author aleja
 */
public class Login_Registro_Escolar extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_de_Sesion_Inventario
     */
    public Login_Registro_Escolar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo_del_Programa = new javax.swing.JLabel();
        Simbolo_Marca_Registrada = new javax.swing.JLabel();
        Descripcion_del_Programa = new javax.swing.JLabel();
        jLabel_Bienvenida = new javax.swing.JLabel();
        jLabel_Porfavor_inicie_sesion = new javax.swing.JLabel();
        jLabel_Contraseña = new javax.swing.JLabel();
        jTextField_Nombre_de_usuario = new javax.swing.JTextField();
        jLabel_Usuario = new javax.swing.JLabel();
        jPasswordField_Contraseña = new javax.swing.JPasswordField();
        jButton_Iniciar_Sesion = new javax.swing.JButton();
        jLabel_Logo_del_programa = new javax.swing.JLabel();
        jButton_Volver = new javax.swing.JButton();
        jCheckBox_Mostrar_contraseña = new javax.swing.JCheckBox();
        jLabel_Ojo_Oculto = new javax.swing.JLabel();
        jLabel_Ojo_Visible = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton_Solicitar_inscripcion = new javax.swing.JButton();
        Imagen_de_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(839, 715));
        setMinimumSize(new java.awt.Dimension(839, 715));
        setPreferredSize(new java.awt.Dimension(839, 715));
        setResizable(false);
        getContentPane().setLayout(null);

        Titulo_del_Programa.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        Titulo_del_Programa.setForeground(new java.awt.Color(0, 0, 102));
        Titulo_del_Programa.setText("LogBook");
        getContentPane().add(Titulo_del_Programa);
        Titulo_del_Programa.setBounds(480, 30, 210, 67);

        Simbolo_Marca_Registrada.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        Simbolo_Marca_Registrada.setForeground(new java.awt.Color(0, 0, 102));
        Simbolo_Marca_Registrada.setText("®");
        getContentPane().add(Simbolo_Marca_Registrada);
        Simbolo_Marca_Registrada.setBounds(690, 40, 20, 20);

        Descripcion_del_Programa.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        Descripcion_del_Programa.setText("Sistema de registro escolar");
        getContentPane().add(Descripcion_del_Programa);
        Descripcion_del_Programa.setBounds(480, 90, 220, 30);

        jLabel_Bienvenida.setFont(new java.awt.Font("Leelawadee", 1, 26)); // NOI18N
        jLabel_Bienvenida.setForeground(new java.awt.Color(0, 0, 102));
        jLabel_Bienvenida.setText("¡Bienvenido al gestor de registro escolar!");
        getContentPane().add(jLabel_Bienvenida);
        jLabel_Bienvenida.setBounds(280, 160, 520, 40);

        jLabel_Porfavor_inicie_sesion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel_Porfavor_inicie_sesion.setText("Por favor inicie sesión para poder ver su menú principal");
        getContentPane().add(jLabel_Porfavor_inicie_sesion);
        jLabel_Porfavor_inicie_sesion.setBounds(210, 210, 560, 30);

        jLabel_Contraseña.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel_Contraseña.setForeground(new java.awt.Color(0, 0, 102));
        jLabel_Contraseña.setText("Contraseña:");
        getContentPane().add(jLabel_Contraseña);
        jLabel_Contraseña.setBounds(320, 350, 110, 30);

        jTextField_Nombre_de_usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_Nombre_de_usuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_Nombre_de_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Nombre_de_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Nombre_de_usuario);
        jTextField_Nombre_de_usuario.setBounds(230, 290, 280, 40);

        jLabel_Usuario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel_Usuario.setForeground(new java.awt.Color(0, 0, 102));
        jLabel_Usuario.setText("Usuario:");
        getContentPane().add(jLabel_Usuario);
        jLabel_Usuario.setBounds(230, 260, 80, 30);

        jPasswordField_Contraseña.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPasswordField_Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_ContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField_Contraseña);
        jPasswordField_Contraseña.setBounds(320, 380, 280, 40);

        jButton_Iniciar_Sesion.setBackground(new java.awt.Color(71, 152, 30));
        jButton_Iniciar_Sesion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Iniciar_Sesion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Iniciar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_del_Registro_Escolar/Logo iniciar sesion blanco CHICO.png"))); // NOI18N
        jButton_Iniciar_Sesion.setText(" Iniciar sesión");
        jButton_Iniciar_Sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Iniciar_Sesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_Iniciar_Sesion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton_Iniciar_Sesion.setIconTextGap(2);
        jButton_Iniciar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Iniciar_SesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Iniciar_Sesion);
        jButton_Iniciar_Sesion.setBounds(430, 470, 240, 50);

        jLabel_Logo_del_programa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_del_Registro_Escolar/Logotipo de LogBook CHICO.png"))); // NOI18N
        getContentPane().add(jLabel_Logo_del_programa);
        jLabel_Logo_del_programa.setBounds(720, 20, 80, 110);

        jButton_Volver.setBackground(new java.awt.Color(255, 153, 0));
        jButton_Volver.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton_Volver.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_del_Registro_Escolar/Logo volver blanco CHICO.png"))); // NOI18N
        jButton_Volver.setText(" Volver al menu principal");
        jButton_Volver.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Volver);
        jButton_Volver.setBounds(20, 620, 357, 45);

        jCheckBox_Mostrar_contraseña.setBackground(new java.awt.Color(255, 255, 204));
        jCheckBox_Mostrar_contraseña.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jCheckBox_Mostrar_contraseña.setText("Mostrar contraseña");
        jCheckBox_Mostrar_contraseña.setToolTipText("");
        jCheckBox_Mostrar_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_Mostrar_contraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_Mostrar_contraseña);
        jCheckBox_Mostrar_contraseña.setBounds(420, 430, 180, 20);

        jLabel_Ojo_Oculto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_del_Registro_Escolar/Icono ojo OCULTO.png"))); // NOI18N
        getContentPane().add(jLabel_Ojo_Oculto);
        jLabel_Ojo_Oculto.setBounds(610, 390, 30, 20);

        jLabel_Ojo_Visible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_del_Registro_Escolar/Icono ojo VISIBLE.png"))); // NOI18N
        getContentPane().add(jLabel_Ojo_Visible);
        jLabel_Ojo_Visible.setBounds(610, 390, 30, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("¿Eres nuevo alumno?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(490, 560, 190, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(420, 540, 410, 20);

        jButton_Solicitar_inscripcion.setBackground(new java.awt.Color(0, 153, 255));
        jButton_Solicitar_inscripcion.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jButton_Solicitar_inscripcion.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Solicitar_inscripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_del_Registro_Escolar/Icono Registrar CHICO.png"))); // NOI18N
        jButton_Solicitar_inscripcion.setText("Solicitar inscripción");
        jButton_Solicitar_inscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Solicitar_inscripcionActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Solicitar_inscripcion);
        jButton_Solicitar_inscripcion.setBounds(490, 600, 270, 45);

        Imagen_de_Fondo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Imagen_de_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_del_Registro_Escolar/Imagen para inicio de sesion de Registro Escolar AJUSTADO.png"))); // NOI18N
        Imagen_de_Fondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Imagen_de_Fondo.setMaximumSize(new java.awt.Dimension(839, 688));
        Imagen_de_Fondo.setMinimumSize(new java.awt.Dimension(839, 688));
        Imagen_de_Fondo.setPreferredSize(new java.awt.Dimension(839, 688));
        getContentPane().add(Imagen_de_Fondo);
        Imagen_de_Fondo.setBounds(0, 0, 840, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Nombre_de_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Nombre_de_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Nombre_de_usuarioActionPerformed

    private void jButton_Iniciar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Iniciar_SesionActionPerformed
        String Nombre_de_usuario = "Alejandro Machado";
        String Contraseña = "AlejM34";
        String Password_Vacio = "";

        String password = new String(this.jPasswordField_Contraseña.getPassword());

//CONDICIONAMOS QUE LOS CAMPOS NO PUEDAN ESTAR VACIOS
        if (jTextField_Nombre_de_usuario.getText().isEmpty() || password.equals(Password_Vacio)) {

            JOptionPane.showMessageDialog(this, "NO se pueden dejar espacios vacios, ingrese correctamente los datos");
        } else {

// VALIDAMOS EL ACCESO AL USUARIO
            if (this.jTextField_Nombre_de_usuario.getText().equals(Nombre_de_usuario) && password.equals(Contraseña)) {

                JOptionPane.showMessageDialog(this, "Datos correctamente ingresados. Bienvenido al sistema :D");

                Menu_Principal_ADMINISTRADOR Ventana = new Menu_Principal_ADMINISTRADOR();
                Ventana.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Los datos son incorrectos. Vuelva a intentarlo");
            }
        }
    }//GEN-LAST:event_jButton_Iniciar_SesionActionPerformed

    private void jPasswordField_ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_ContraseñaActionPerformed

    private void jButton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VolverActionPerformed
        Login_Seleccion_de_usuarios Ventana = new Login_Seleccion_de_usuarios();
        Ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_VolverActionPerformed

    private void jCheckBox_Mostrar_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_Mostrar_contraseñaActionPerformed
        if (jCheckBox_Mostrar_contraseña.isSelected()) {
            jPasswordField_Contraseña.setEchoChar((char) 0);
            jLabel_Ojo_Oculto.setVisible(false);
           
        } else {
            jPasswordField_Contraseña.setEchoChar('*');
            jLabel_Ojo_Oculto.setVisible(true);
            
        }
    }//GEN-LAST:event_jCheckBox_Mostrar_contraseñaActionPerformed

    private void jButton_Solicitar_inscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Solicitar_inscripcionActionPerformed
        Solicitud_de_ingreso Formulario = new Solicitud_de_ingreso();
        Formulario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_Solicitar_inscripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Registro_Escolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Registro_Escolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Registro_Escolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Registro_Escolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Registro_Escolar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripcion_del_Programa;
    private javax.swing.JLabel Imagen_de_Fondo;
    private javax.swing.JLabel Simbolo_Marca_Registrada;
    private javax.swing.JLabel Titulo_del_Programa;
    private javax.swing.JButton jButton_Iniciar_Sesion;
    private javax.swing.JButton jButton_Solicitar_inscripcion;
    private javax.swing.JButton jButton_Volver;
    private javax.swing.JCheckBox jCheckBox_Mostrar_contraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Bienvenida;
    private javax.swing.JLabel jLabel_Contraseña;
    private javax.swing.JLabel jLabel_Logo_del_programa;
    private javax.swing.JLabel jLabel_Ojo_Oculto;
    private javax.swing.JLabel jLabel_Ojo_Visible;
    private javax.swing.JLabel jLabel_Porfavor_inicie_sesion;
    private javax.swing.JLabel jLabel_Usuario;
    private javax.swing.JPasswordField jPasswordField_Contraseña;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField_Nombre_de_usuario;
    // End of variables declaration//GEN-END:variables
}
