/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases_Principales;

import java.util.Locale;
import javax.swing.JTable;

/**
 *
 * @author aleja
 */
public class Menu_Principal_ALUMNO extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal_ADMINISTRADOR
     */
    public Menu_Principal_ALUMNO() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Servicios_escolares = new javax.swing.JLabel();
        Titulo_del_Programa = new javax.swing.JLabel();
        jLabel_Logo_LogBook = new javax.swing.JLabel();
        Simbolo_Marca_Registrada = new javax.swing.JLabel();
        Descripcion_del_Programa = new javax.swing.JLabel();
        jButton_Actualizar_info = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Menu_principal = new javax.swing.JLabel();
        Separator_Lista_de_prospectos = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Fondo_verde = new javax.swing.JLabel();
        jLabel_Fondo_azul = new javax.swing.JLabel();
        jLabel_Fondo_azul_oscuro = new javax.swing.JLabel();
        jLabel_Fondo_Gris = new javax.swing.JLabel();
        jLabel_Fondo_blanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal Administrador - LogBook");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1097, 670));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel_Servicios_escolares.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel_Servicios_escolares.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Servicios_escolares.setText("Opciones");
        getContentPane().add(jLabel_Servicios_escolares);
        jLabel_Servicios_escolares.setBounds(10, 90, 100, 30);

        Titulo_del_Programa.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Titulo_del_Programa.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_del_Programa.setText("LogBook");
        Titulo_del_Programa.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(Titulo_del_Programa);
        Titulo_del_Programa.setBounds(10, 11, 130, 40);

        jLabel_Logo_LogBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_del_Registro_Escolar/Logotipo de LogBook MAS CHICO.png"))); // NOI18N
        getContentPane().add(jLabel_Logo_LogBook);
        jLabel_Logo_LogBook.setBounds(190, 10, 50, 60);

        Simbolo_Marca_Registrada.setFont(new java.awt.Font("Gill Sans MT", 1, 16)); // NOI18N
        Simbolo_Marca_Registrada.setForeground(new java.awt.Color(255, 255, 255));
        Simbolo_Marca_Registrada.setText("®");
        getContentPane().add(Simbolo_Marca_Registrada);
        Simbolo_Marca_Registrada.setBounds(135, 15, 20, 20);

        Descripcion_del_Programa.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Descripcion_del_Programa.setForeground(new java.awt.Color(255, 255, 255));
        Descripcion_del_Programa.setText("Sistema de registro escolar");
        getContentPane().add(Descripcion_del_Programa);
        Descripcion_del_Programa.setBounds(10, 40, 180, 30);

        jButton_Actualizar_info.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Actualizar_info.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jButton_Actualizar_info.setText("Actualizar información");
        jButton_Actualizar_info.setToolTipText("Muestra la lista de los alumnos que ya han sido admitidos en el la institucion");
        jButton_Actualizar_info.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_Actualizar_info.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jButton_Actualizar_info);
        jButton_Actualizar_info.setBounds(10, 220, 230, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Informacion ingresada");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 100, 260, 32);

        jLabel_Menu_principal.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel_Menu_principal.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Menu_principal.setText("Menú principal");
        getContentPane().add(jLabel_Menu_principal);
        jLabel_Menu_principal.setBounds(270, 20, 210, 40);
        getContentPane().add(Separator_Lista_de_prospectos);
        Separator_Lista_de_prospectos.setBounds(270, 140, 810, 20);

        jPanel1.setMaximumSize(new java.awt.Dimension(710, 390));
        jPanel1.setMinimumSize(new java.awt.Dimension(710, 390));
        jPanel1.setPreferredSize(new java.awt.Dimension(710, 390));
        jPanel1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(270, 170, 800, 390);

        jLabel_Fondo_verde.setBackground(new java.awt.Color(45, 132, 45));
        jLabel_Fondo_verde.setOpaque(true);
        getContentPane().add(jLabel_Fondo_verde);
        jLabel_Fondo_verde.setBounds(0, 80, 250, 50);

        jLabel_Fondo_azul.setBackground(new java.awt.Color(0, 136, 182));
        jLabel_Fondo_azul.setOpaque(true);
        getContentPane().add(jLabel_Fondo_azul);
        jLabel_Fondo_azul.setBounds(0, 0, 250, 80);

        jLabel_Fondo_azul_oscuro.setBackground(new java.awt.Color(7, 43, 78));
        jLabel_Fondo_azul_oscuro.setForeground(new java.awt.Color(36, 36, 36));
        jLabel_Fondo_azul_oscuro.setOpaque(true);
        getContentPane().add(jLabel_Fondo_azul_oscuro);
        jLabel_Fondo_azul_oscuro.setBounds(250, 0, 840, 80);

        jLabel_Fondo_Gris.setBackground(new java.awt.Color(243, 243, 243));
        jLabel_Fondo_Gris.setOpaque(true);
        getContentPane().add(jLabel_Fondo_Gris);
        jLabel_Fondo_Gris.setBounds(0, 130, 250, 520);

        jLabel_Fondo_blanco.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Fondo_blanco.setOpaque(true);
        getContentPane().add(jLabel_Fondo_blanco);
        jLabel_Fondo_blanco.setBounds(250, 80, 840, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal_ALUMNO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal_ALUMNO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal_ALUMNO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal_ALUMNO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal_ALUMNO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripcion_del_Programa;
    private javax.swing.JSeparator Separator_Lista_de_prospectos;
    private javax.swing.JLabel Simbolo_Marca_Registrada;
    private javax.swing.JLabel Titulo_del_Programa;
    private javax.swing.JButton jButton_Actualizar_info;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Fondo_Gris;
    private javax.swing.JLabel jLabel_Fondo_azul;
    private javax.swing.JLabel jLabel_Fondo_azul_oscuro;
    private javax.swing.JLabel jLabel_Fondo_blanco;
    private javax.swing.JLabel jLabel_Fondo_verde;
    private javax.swing.JLabel jLabel_Logo_LogBook;
    private javax.swing.JLabel jLabel_Menu_principal;
    private javax.swing.JLabel jLabel_Servicios_escolares;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
